name: terraform-plan
on: [pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envdir: [envs/dev] 
    defaults:
      run:
        working-directory: ${{ matrix.envdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Init
        run: terraform init -input=false
      - name: Plan
        run: terraform plan -input=false -no-color -var="region=us-east-1" -var="name=demo"
